# .golangci.yml
version: 2
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  # Define output format
  output:
    format: colored-line-number
