# Architect Configuration File
# This is an example configuration file with all available options

# General configuration options
output_file = "PLAN.md"  # Output file for generated plans
model = "gemini-2.5-pro-exp-03-25"  # Gemini model to use
format = "<{path}>\n```\n{content}\n```\n</{path}>\n\n"  # Format for code snippets
confirm_tokens = 0  # Token threshold for confirmation (0 = never prompt)

# Include patterns (comma-separated list)
include = ""  # Leave empty to include all file types

# Display options
verbose = false  # Enable verbose logging
log_level = "info"  # Log level (debug, info, warn, error)
use_colors = true  # Use colored output
no_spinner = false  # Disable spinner animation

# Template settings
[templates]
default = "default.tmpl"  # Main template for generating plans
dir = "templates"  # Custom template directory (relative to config dir or absolute)

# File exclusion patterns
[excludes]
# File extensions to exclude (comma-separated)
extensions = ".exe,.bin,.obj,.o,.a,.lib,.so,.dll,.dylib,.class,.jar,.pyc,.pyo,.pyd,.zip,.tar,.gz,.rar,.7z,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.odt,.ods,.odp,.jpg,.jpeg,.png,.gif,.bmp,.tiff,.svg,.mp3,.wav,.ogg,.mp4,.avi,.mov,.wmv,.flv,.iso,.img,.dmg,.db,.sqlite,.log"

# File and directory names to exclude (comma-separated)
names = ".git,.hg,.svn,node_modules,bower_components,vendor,target,dist,build,out,tmp,coverage,__pycache__,*.pyc,*.pyo,.DS_Store,~$*,desktop.ini,Thumbs.db,package-lock.json,yarn.lock,go.sum,go.work"